# Generated by Django 4.2.6 on 2023-10-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motos',
            name='brand',
        ),
    ]
