# Generated by Django 4.2.6 on 2023-10-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_remove_motos_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Motos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
